<hr style="margin-bottom: 40px;">

# Homework 4. Gradebook 3

**Chapter**: Unit 4. pandas Basics

**Core knowledge**: pandas Series, pandas DataFrame, essential pandas functionality, descriptive statistics with pandas

**Your task**: Expanding on earlier exercises, you will be using not only the student gradebook from last time (gradebook_ex2.csv) but also a new dataset which includes the students sleeping and study hours (gradebook_ex3.csv). You are asked to perform the following tasks:

* **Student Roster Analysis**: conduct an analysis on student names and classes, including but not limited to finding the number of students in each class, finding if there's any repetitive student names, sort/group student names in alphabetical order.
* **Exam Grade Analysis**: similar to HW3, including but not limited to calculating the average grade, max grade, min grade, standard deviation, and number of absences for each of the 5 exams. All float values should be rounded to 2 decimal places.
* **Student Grade Analysis**: similar to HW3, including but not limited to calculating the average grade across the 5 exams, sorting/ranking the students by average grade, and counting the number of fails (grade < 60) or absences to determine whether the student need to make up (at least 2 fails or absences).
* **Correlational Analysis**: conduct correlational statistical analysis with the two datasets, such as finding the correlation between the average grades of students and their sleeping/study hours.

**Test gradebook**: You may use the example file "gradebook_ex2.csv" and "gradebook_ex3.csv" for testing.

In [3]:
path1 = "gradebook_ex2.csv"
path2 = "gradebook_ex3.csv"

In [1]:
# Your imports go here:
import numpy as np
import pandas as pd

In [ ]:
# Your functions go here:

In [55]:
# Your test cases go here:
data1 = pd.read_csv(path1, na_values=-1) # sentinel values for NA
data2 = pd.read_csv(path2, index_col = ["Name", "Class"])
# data1.replace(-1, pd.NA)
data1
data3 = pd.read_csv(path1, na_values=-1, index_col = ["Name", "Class"])
data3

                Grade 1  Grade 2  Grade 3  Grade 4  Grade 5
Name     Class
Elton    10(1)     57.0       68     72.0     53.0       79
Harry    10(1)     84.0       77     56.0     66.0       67
Lawrence 10(2)     78.0       56     80.0     61.0       79
Annie    10(3)     92.0       81      NaN     85.0       91
Ricky    10(3)     88.0       79     61.0     74.0       87
Penny    10(4)     90.0       65     72.0     83.0       62
Danny    10(4)     76.0       70     82.0     62.0       50
Jacky    10(4)     89.0       79     75.0     76.0       76
Kevin    10(4)     93.0      100     88.0      NaN       93
Ivan     10(5)     76.0       86     72.0     85.0       98
Matthew  10(6)      NaN       64     50.0     55.0       43
Franklin 10(6)     85.0       55     75.0     61.0       87
Eric     10(7)     61.0       62     55.0     58.0       63
Ena      10(8)     57.0       90     89.0     89.0       77
Harry    10(8)     60.0       73     64.0     71.0       69

In [13]:
# Find if there's any repetitive names
name_count = data1["Name"].value_counts()
name_count[name_count != 1]

Name
Harry    2
Name: count, dtype: int64

In [18]:
# Find the number of students in each class
print(data1["Class"].value_counts().sort_index())
for key, group in data1.groupby("Class")["Name"]: # Aggregate function
    print(f"{key}:")
    print(f"{list(group)}")

Class
10(1)    2
10(2)    1
10(3)    2
10(4)    4
10(5)    1
10(6)    2
10(7)    1
10(8)    2
Name: count, dtype: int64
10(1):
['Elton', 'Harry']
10(2):
['Lawrence']
10(3):
['Annie', 'Ricky']
10(4):
['Penny', 'Danny', 'Jacky', 'Kevin']
10(5):
['Ivan']
10(6):
['Matthew', 'Franklin']
10(7):
['Eric']
10(8):
['Ena', 'Harry']

In [23]:
exam_anal = data1.describe().round(2)
# count: the count of non-NA values (students who actually attend)
exam_anal.loc["mean"]
# sort the 5 exams by their average grade in descending order
exam_anal.sort_values("mean", axis="columns", ascending=False)

       Grade 1  Grade 5  Grade 2  Grade 3  Grade 4
count    14.00    15.00    15.00    14.00    14.00
mean     77.57    74.73    73.67    70.79    69.93
std      13.51    15.80    12.66    12.15    12.19
min      57.00    43.00    55.00    50.00    53.00
25%      64.75    65.00    64.50    61.75    61.00
50%      81.00    77.00    73.00    72.00    68.50
75%      88.75    87.00    80.00    78.75    81.25
max      93.00    98.00   100.00    89.00    89.00

In [62]:
# Student sorted by grade in descending order
data3.T
std_anal = data3.T.describe().round(2)
std_anal.sort_values("mean", axis="columns", ascending=False).T

                count   mean    std   min    25%   50%    75%    max
Name     Class
Kevin    10(4)    4.0  93.50   4.93  88.0  91.75  93.0  94.75  100.0
Annie    10(3)    4.0  87.25   5.19  81.0  84.00  88.0  91.25   92.0
Ivan     10(5)    5.0  83.40  10.09  72.0  76.00  85.0  86.00   98.0
Ena      10(8)    5.0  80.40  14.14  57.0  77.00  89.0  89.00   90.0
Jacky    10(4)    5.0  79.00   5.79  75.0  76.00  76.0  79.00   89.0
Ricky    10(3)    5.0  77.80  11.03  61.0  74.00  79.0  87.00   88.0
Penny    10(4)    5.0  74.40  11.89  62.0  65.00  72.0  83.00   90.0
Franklin 10(6)    5.0  72.60  14.24  55.0  61.00  75.0  85.00   87.0
Lawrence 10(2)    5.0  70.80  11.39  56.0  61.00  78.0  79.00   80.0
Harry    10(1)    5.0  70.00  10.79  56.0  66.00  67.0  77.00   84.0
Danny    10(4)    5.0  68.00  12.49  50.0  62.00  70.0  76.00   82.0
Harry    10(8)    5.0  67.40   5.32  60.0  64.00  69.0  71.00   73.0
Elton    10(1)    5.0  65.80  10.71  53.0  57.00  68.0  72.00   79.0
Eric     10(7)    5.0  59.80   3.27  55.0  58.00  61.0  62.00   63.0
Matthew  10(6)    4.0  53.00   8.83  43.0  48.25  52.5  57.25   64.0

In [48]:
grades = data1.loc[:, "Grade 1":"Grade 5"]
# Whether each student has at least a fail
fail = grades[grades < 60].any(axis="columns")
# Whether each student has at least an absence
absence = grades.isna().any(axis="columns")
print(fail | absence)

fails = grades[grades < 60].count(axis="columns") # count the number of fails for each student
absences = grades.isna().sum(axis="columns") # count the number of absences for each student
print(fails + absences)

# Make-up list: at least two fails or absences
makeup = fails + absences
makeup[makeup >= 2]
data1["Name"][makeup[makeup >= 2].index]

0      True
1      True
2      True
3      True
4     False
5     False
6      True
7     False
8      True
9     False
10     True
11     True
12     True
13     True
14    False
dtype: bool
0     2
1     1
2     1
3     1
4     0
5     0
6     1
7     0
8     1
9     0
10    4
11    1
12    2
13    1
14    0
dtype: int64

0       Elton
10    Matthew
12       Eric
Name: Name, dtype: object

In [61]:
# Study the correlation between grade and study/sleep hours
data2[["#Study hours", "#Sleep hours"]].describe().round(2)

       #Study hours  #Sleep hours
count         15.00         15.00
mean           1.76          7.49
std            0.58          1.17
min            1.10          6.10
25%            1.30          6.55
50%            1.60          7.10
75%            2.30          8.60
max            2.80          9.60

In [60]:
print(std_anal.loc["mean"].corr(data2["#Study hours"]))
print(std_anal.loc["mean"].corr(data2["#Sleep hours"]))

-0.07880261999932002
-0.07069176974576892